name: Pylint

on: 
  push:
  
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup:
    name: Setup Go and gcloud
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: check gcloud
      run: gcloud auth list
  
  compile:
    name: Compile Application
    runs-on: ubuntu-latest
    needs: setup

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: check gcloud
        run: gcloud auth list