name: Backend API CI/CD

on: 
  push:
  
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  compile-and-test:
    name: Compile and test application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backendAPI

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Install dependencies
        run: go mod download
      
      # - name: Run tests
      #   run: go test -v ./...

  file-system-scan:
    name: File System Scan
    runs-on: ubuntu-latest
    needs: compile-and-test
    defaults:
      run:
        working-directory: ./backendAPI

    permissions:
      contents: read
      security-events: write
      actions: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Trivy file system scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: CRITICAL
    
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build Go Application for COdeQL
        run: |
          go build -o go-app
          mv go-app go-app-$GITHUB_SHA

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/languages:${{matrix.language}}"
          