name: Pylint

on: 
  push:
  
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  compile-and-test:
    name: Compile and test application
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Navigate to the backendAPI directory
        run: cd backendAPI/ && ls
      
      - name: Install dependencies
        run: ls
      
      # - name: Run tests
      #   run: go test -v ./...

  file-system-scan:
    name: File System Scan
    runs-on: ubuntu-latest
    needs: compile-and-test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Trivy Root file system scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: rootfs
          ignore-unfixed: true
          format: table
          output: result.txt
          severity: CRITICAL
