name: Pylint

on: 
  push:

jobs:
  setup:
    name: Setup Go and gcloud
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
  
  compile:
    name: Compile Application
    runs-on: ubuntu-latest
    needs: setup

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Check gcloud
        run: gsutil ls